version: '1.0'

services:
  - name: skillpathai-frontend
    image: skillpathai-frontend
    port: 8501
    env:
      - name: API_URL
        value: http://skillpathai-backend:8000
      - name: ENVIRONMENT
        value: production
      - name: SNOWFLAKE_ACCOUNT
        value: ${SNOWFLAKE_ACCOUNT}
      - name: SNOWFLAKE_USER
        value: ${SNOWFLAKE_USER}
      - name: SNOWFLAKE_PASSWORD
        value: ${SNOWFLAKE_PASSWORD}
      - name: SNOWFLAKE_WAREHOUSE
        value: ${SNOWFLAKE_WAREHOUSE}
      - name: SNOWFLAKE_DATABASE
        value: ${SNOWFLAKE_DATABASE}
      - name: SNOWFLAKE_SCHEMA
        value: ${SNOWFLAKE_SCHEMA}
      - name: SNOWFLAKE_ROLE
        value: ${SNOWFLAKE_ROLE}
    resources:
      memory: 2G
      cpu: 1
    restart_policy:
      condition: on-failure
      max_attempts: 3

  - name: skillpathai-backend
    image: skillpathai-backend
    port: 8000
    env:
      - name: ENVIRONMENT
        value: production
      - name: FRONTEND_URL
        value: http://skillpathai-frontend:8501
      - name: SNOWFLAKE_ACCOUNT
        value: ${SNOWFLAKE_ACCOUNT}
      - name: SNOWFLAKE_USER
        value: ${SNOWFLAKE_USER}
      - name: SNOWFLAKE_PASSWORD
        value: ${SNOWFLAKE_PASSWORD}
      - name: SNOWFLAKE_WAREHOUSE
        value: ${SNOWFLAKE_WAREHOUSE}
      - name: SNOWFLAKE_DATABASE
        value: ${SNOWFLAKE_DATABASE}
      - name: SNOWFLAKE_SCHEMA
        value: ${SNOWFLAKE_SCHEMA}
      - name: SNOWFLAKE_ROLE
        value: ${SNOWFLAKE_ROLE}
    resources:
      memory: 2G
      cpu: 1
    restart_policy:
      condition: on-failure
      max_attempts: 3 